# -*- coding: utf-8 -*-
"""Human_Activity_Recognition_PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GG-bvQg7QKnLlNen9v3qIWUbu6EKQ9cX

# Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

"""# Merge Datasets"""

X_train = pd.read_csv('X_train_data_HAR.txt', delim_whitespace=True, header=None)
print(f'Shape Of X_train:-{X_train.shape}')

X_test=pd.read_csv('X_test_data_HAR.txt',delim_whitespace=True,header=None)
print(f'Shape Of X_test:-{X_test.shape}')

y_train = pd.read_csv('y_train_data_HAR.txt',delim_whitespace=True,header=None)
print(f'Shape Of y_train:-{y_train.shape}')

y_test = pd.read_csv('y_test_data_HAR.txt',delim_whitespace=True,header=None)
print(f'Shape Of y_test:-{y_test.shape}')

X = pd.concat([X_train,X_test],axis=0)
y = pd.concat([y_train,y_test],axis=0)

print(f'Shape Of X:-{X.shape}')
print(f'Shape Of y:-{y.shape}')

df = X.copy()
df['target'] = y.values
print(f'Shape Of df:-{df.shape}')
df.sample(5)



"""# Understad Data"""

# Info of Data
df.info()

# Duplicated Record Check
df.duplicated().sum()

# Check NAN Or missing Data
df.isna().sum()[(df.isna().sum()) > 0]

# Top 10 Features With High Varience
df.drop(columns='target').var().sort_values(ascending=False).head(10)

"""# Exploratory Data Analysis"""

# Target Feature Distribution
df.target.value_counts(normalize=True)*100

# Plot of Target Distribution
plt.figure(figsize=(12,6))
sns.countplot(x=df.target,palette='viridis')
plt.show()

# Slightly Imbalance But OK At this level

# Class Seperation Check:-
plt.scatter(df.iloc[:,0], df.iloc[:,1], c=df['target'])
plt.show()

"""## Two individual features are not sufficient to separate the classes.

# Principal-Component-Analysis (PCA)
"""

# Checking For Mean Centered Data:-
df.iloc[:, :-1].mean().head(10)
# Data is not mean-centered: Scaling Needed

# Scaling Data

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df.iloc[:,:-1])

pd.DataFrame(X_scaled).mean().sample(5)
# Now Features Are MEan Centered

# Create Pca Object:-

pca = PCA()

X_pca = pca.fit_transform(X_scaled)

# Explained varience:-
explained_varience = np.cumsum(pca.explained_variance_ratio_)

# Scree Plot To Find Out Optimal Principal Components:
plt.figure(figsize=(12,6))
plt.plot(explained_varience)
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.show()

# Apply PCA With Choosen Component:-
pca = PCA(n_components=125)
X_pca_final = pca.fit_transform(X_scaled)
print(f'Shape Of X_pca_final:-{X_pca_final.shape}')

# 2-D Plot PCA

pca_2 = PCA(n_components=2)
X_pca_2 = pca_2.fit_transform(X_scaled)

plt.figure(figsize=(12,6))
sns.scatterplot(x=X_pca_2[:,0],y=X_pca_2[:,1],hue=df.target)
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""### Initial visualization using raw features showed no clear separation. After applying PCA, the data revealed underlying structure with partial class separation, indicating that PCA successfully captured important variance in the data

# Model-1:- Without-PCA
"""

# Logistic Regression Without PCA:-

X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=42)

model1 = LogisticRegression(max_iter=1000)

model1.fit(X_train,y_train)

y_pred = model1.predict(X_test)

print(f'Accuracy Score Without-PCA:-{accuracy_score(y_test,y_pred)}')

"""# Model-2:- With PCA"""

# Logistic Regression With PCA (125 PCA Features):-

X_train_pca,X_test_pca,y_train_pca,y_test_pca = train_test_split(X_pca_final,y,test_size=0.2,random_state=42)

model2 = LogisticRegression(max_iter=1000)

model2.fit(X_train_pca,y_train_pca)

y_pred_pca = model2.predict(X_test_pca)

print(f'Accuracy Score With PCA:-{accuracy_score(y_test_pca,y_pred_pca)}')

"""# Conclusion:-

### Applying PCA reduced the feature space from `561 to 125` dimensions while retaining comparable model performance `only ~1% drop in accuracy`, significantly improving computational efficiency.

### PCA proved to be a powerful technique for balancing model efficiency and performance, making it highly valuable for real-world high-dimensional datasets where scalability and speed are critical.
"""